config/routes.rb
Rails.application.routes.draw do
  resources :genres
  get "movies/filter/:filter" => "movies#index", as: :filtered_movies
  resources :users
  get "signup" =>"users#new"
  # verb "url" => "movie#index"
  get 'movies/index'
  resources :movies do
    resources :reviews
    resources :favorites, only: [:create,:destroy]
  end

  resource :session, only: [:new, :create, :destroy]
  get "signin" => "sessions#new"
  
  root  'movies#index'
  
  
 
  # get "/flix", to: "movies#index"
  # get "/flix/:id", to: "movies#show", as: "movie"
  # get "/flix/:id/edit", to: "movies#edit", as: "movie_edit"
  # patch "/flix/:id" => "movies#update"
  # get "/flix/new", to: "movies#new"
  # get "/flix", to: "movies#manoj"
end

app/models/user.rb
class User < ApplicationRecord
  before_save :formate_username
  before_save :set_slug

  has_secure_password
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_movies, through: :favorites, source: :movie

  validates :name, presence: true
  validates :email, presence: true,
    format:{ with: /\S+@\S+/ }, uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: {minimum: 6,allow_blank: true}
  validates :username,presence: true,
    format: {with: /\A[A-Z0-9]+\z/i },uniqueness: {case_sensitive: false}

  scope :by_name, -> { order(:name) }
  scope :not_admin, -> { by_name.where(admin: false) }

  def gravatar_id
    Digest::MD5::hexdigest(email.downcase)
  end

    # def to_param
    #   slug
    # end

  private 

  def formate_username
    self.username = username.downcase
  end

  def set_slug
    self.slug = name.parameterize
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_signin, except: [:new, :create]
    
    before_action :require_correct_user, only: [:edit, :update, :destroy]
    
    before_action :require_admin, only: [:destroy]
    

    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
        @reviews = @user.reviews    
        @favorite_movies = @user.favorite_movies
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id]=@user.id
            redirect_to @user, notice: "Thanks for signing up"
        else
            render :new,status: :unprocessable_entity
        end
    end

    def edit
        # @user = User.find(params[:id])
    end

    def update
        # @user = User.find(params[:id])
        # binding.pry
        if @user.update(user_params)
            flash[:notice] = "User Successfully updated!"
            redirect_to @user
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        # @user = User.find(params[:id])
        @user.destroy
        session[:user_id]=nil
        redirect_to users_url, notice: "User Successfully Deleted!",status: :see_other
    end

    private

    def require_correct_user
        @user = User.find(params[:id])
        unless current_user?(@user)
            redirect_to root_url,status: :see_other
        end
    end
    
    def user_params
        params.require(:user).permit(:name,:email,:password,:password_confirmation,:username,:admin)
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def profile_image(user,size=80)
        url = "https://secure.gravatar.com/avatar/#{user.gravatar_id}"
        image_tag(url,alt: user.name)
    end
end

app/views/users/_form.html.erb
<%= form_with(model:user) do |f|%>
   <%= render "senders/errors",object: user%>
   <%= f.label :name%>
   <%= f.text_field :name,autofocus: true%>
   <%= f.label :email%>
   <%= f.email_field :email%>
   <%= f.label :password%>
   <%= f.password_field :password%>
   <%= f.label :password_confirmation, "Confirm Password" %>
   <%= f.password_field :password_confirmation%>
   <%= f.label :username%>
   <%= f.text_field :username,placeholder: "Alphanumeric characters only!" %>
   <% if user.new_record?%>
      <%= f.submit "Create Account" %>
   <% else %>
       <%= f.submit "Update Account" %>
    <% end %>
<% end %> 

app/views/users/edit.html.erb
<h1>Edit User Details </h1>
 <%= render "form", user:@user%>

app/views/users/index.html.erb
<h1><%= pluralize(@users.size,"User") %></h1>
<ul class="users">
    <% @users.each do |user|%>
        <li>
            <%= link_to user.name.capitalize, user %>
            created
            <%= time_ago_in_words(user.created_at)%>
        </li>
    <% end %>
</ul>

<div>
    <%= link_to "Create User", signup_path, class:"button"%>
</div>

app/views/users/new.html.erb
<h1> Create Account </h1>

<%= render "form",user: @user%>

app/views/users/show.html.erb
<h1> WELCOME TO USER DETAILS </h1><br><hr><br>
<section class="user">   
<%= profile_image(@user)%>
    <h1><%= @user.name%></h1>
    <h1><%= @user.username%></h1>
    <h1><%= mail_to(@user.email)%></h2>
    <h3>Member Since</h3>
    <p><%= @user.created_at.strftime("%B %Y")%></p>
</section>


    <% if @favorite_movies.present? %>
        <h3>Favorite Movies</h3>
        <div class="favorite-movies">
            <% @favorite_movies.each do |movie|%>
                <%# <%= link_to image_tag(movie.image_file_name),movie %> 
                <%= link_to movie.name , movie %><br>
            <%end%>
        </div>
    <% end %>


<section class="user">
<% if @reviews.present? %>
    <h3>Reviews</h3>
    <% @reviews.each do |review| %>
        <div class="review">
            <div class="details">
                <%# <%= image_tag(review.movie.image_file_name,size)%> 
                <span class="title">
                    <%= link_to review.movie.name, review.movie %>
                </span>
         <%= pluralize(review.stars, 'star') %>
                <span class="date">
                    <%= time_ago_in_words(review.created_at) %> ago
                </span>
                <p>
                    <%= review.comment %>
                </p>
            </div>
        </div>
    <% end%>
<%end%>
</section>
<section class="admin">
    <% if current_user?(@user) %>
        <%= link_to "Edit", edit_user_path(@user),class: "button" %>
    <% end %>
    <% if current_user_admin? %>
        <%= link_to "Delete", user_path(@user), class: "button",
         data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %><br><br>
    <% end%>
</section>

<div class="actions">
    <%= link_to "Back to all user",users_path(@user), class: "button" %>
</div>