config/routes.rb
Rails.application.routes.draw do
  resources :genres
  get "movies/filter/:filter" => "movies#index", as: :filtered_movies
  resources :users
  get "signup" =>"users#new"
  # verb "url" => "movie#index"
  get 'movies/index'
  resources :movies do
    resources :reviews
    resources :favorites, only: [:create,:destroy]
  end

  resource :session, only: [:new, :create, :destroy]
  get "signin" => "sessions#new"
  
  root  'movies#index'
  
  
 
  # get "/flix", to: "movies#index"
  # get "/flix/:id", to: "movies#show", as: "movie"
  # get "/flix/:id/edit", to: "movies#edit", as: "movie_edit"
  # patch "/flix/:id" => "movies#update"
  # get "/flix/new", to: "movies#new"
  # get "/flix", to: "movies#manoj"
end

app/views/layouts/_flash.html.erb
 <% if flash[:notice] %>
    <div class = "flash notice">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
  <div class="flash alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
     <p>Made By <a href = "mailto: manoj.solanki@example.com">manoj.solanki@gemsessence</a></p>
</footer>

app/views/layouts/_header.html.erb
<header>
      <nav>
        <h1><%=link_to image_tag("logo.png"), root_path%></h1>
        <ul class="left">
          <%# <a href="/movies_path">All Movies</a> %>
          <li> <%= nav_link_to "All Movies", movies_path%></li>
           <li><%= nav_link_to "Upcoming Movie",filtered_movies_path(:upcoming)%></li>
           <li><%= nav_link_to "Recent",filtered_movies_path("recent")%></li>
           <li><%= nav_link_to "Hits", filtered_movies_path("hits") %></li>
           <li><%= nav_link_to "flops", filtered_movies_path(:flops) %></li>
        </ul>
        <ul class="right">
        <% if current_user %>
          <li><%=  link_to current_user.name, user_path(current_user)%></li>
          <li><%= link_to "Account Settings",edit_user_path(current_user) %></li>
          <li><%= link_to "Sign Out!",session_path,data: {turbo_method: :delete},class: "button"%>
        <% else %>
          <li><%= link_to "Sign in", signin_path, class: "button"  %></li>
          <li><%= link_to "Sign Up",signup_path, class: "button"%>
        <% end %>
        </ul>
      </nav>    
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flix</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  
  </head>

  <body>

     <%= render "layouts/header" %>
     
    <div class="contend">
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>  
  
    <%= render "layouts/footer" %>
  </body>
</html>